### ISSUE TITLE
GSF Exec Podcast

### ISSUE THREAD

**Issue by Jenya-design** [Green-Software-Foundation/cxo-bytes-podcast#4]
GSF Exec Podcast - name is the work in progress, the task is paused till the name is finalized

Scope of the work (as discussed with Chris):

- [ ] Logo
- [ ] General thumbnail. Which needs to be a 3000 x 3000 px Square. 
- [ ] Episode specific thumbnail where we can put the guests profile picture, episode number, title and guest name.
- [ ] YouTube thumbnail where we can do the same

Then Design folder  with examples - [here](https://drive.google.com/drive/folders/1py8s_vvTY3eFfUENHknLVQuDohHxFYdz?usp=sharing)

Related issue Initiative - Exec Podcast Green-Software-Foundation/gsf-admin#454

**Comment by Jenya-design** [comment]
@zanete I think this issue was closed by mistake, the task is in progress. Can I reopen it?

**Comment by sonicfutures** [comment]
@russelltrow @zanete I think the automation on this project is incorrect. This issue should still be open.

**Comment by zanete** [comment]
@sonicfutures @Jenya-design @russelltrow i'm not sure how I managed to close it, I definitely didn't mean to, apologies for the confusion!

**Comment by Jenya-design** [comment]
@sonicfutures @russelltrow please check the first update here
https://drive.google.com/file/d/1xDsUb-ZSCSHn3uK_WcHShme8sY1g84Iv/view?usp=sharing
There are 3 logo concepts and related thumbnail designs in two colors 
Let me know what you think

**Comment by sonicfutures** [comment]
@Jenya-design This is AWESOME. Love all 3 of them. I think my favourite is **number 2**.

@russelltrow Any thoughts?

**Comment by russelltrow** [comment]
@bryaki02 will be PMing this project so I'll let her share her thoughts :)

**Comment by bryaki02** [comment]
@sonicfutures I agree! I think number 2 and number 1 are my favourites. Really great @Jenya-design

**Comment by Jenya-design** [comment]
Thank you @sonicfutures @bryaki02 I'm very happy enjoy the design!
I'll continue with the concept 2 and the rest of items from our list, please let me know if you have any additional comments or suggestions.
@sonicfutures which file format of the thumbnails works best for you? Do you have a specific deadline  for the next update in mind?

**Comment by sonicfutures** [comment]
Awesome @Jenya-design. Yes please continue. It would be awesome to have just standard .PNG and .JPG files as big as possible at first so that we can then compress them for upload. It would be nice to see something by the end of the week if that's possible? So **EOD on Friday 14 June**? Let me know if that's ok. Hoping to get the first episode up by the end of next week.

**Comment by Jenya-design** [comment]
@sonicfutures sure, you'll have the update by EOD June 14

**Comment by Jenya-design** [comment]
@sonicfutures @russelltrow can I have the title of the 1st episode and the photo of Dr. Ong Chen Hui - 1st guest?

**Comment by sonicfutures** [comment]
@Jenya-design Let's just go with: **Greening Digital Sustainability with Dr. Ong Chen Hui**

Please refer back to the examples in here to see how the parts of the title should be laid out please: https://drive.google.com/drive/folders/1tbwhmq304XLxzfbL6wIKxjREQ-9wtZJJ?usp=drive_link

For the profile pic please use this one here: https://www.linkedin.com/in/ong-chenhui/?originalSubdomain=sg

**Comment by Jenya-design** [comment]
@russelltrow @sonicfutures please check the thumbnails preview attached (size 3000x3000 and 2560x1440) 
Individual files for each thumbnail and logo [are here](https://drive.google.com/drive/folders/1fjytlrhhUqpBWS4xoyzZbDbNU6kJOSm8?usp=drive_link) (backup on GSF drive [here](https://drive.google.com/drive/folders/1zjo4Rtn-pKU4IUAJH4S8meCYCx5WnXLs?usp=drive_link)). I've picked black version to proceed so it stands out better in GSF social feed
Please let me know if you need any adjustments

![Image](https://github.com/Green-Software-Foundation/cxo-bytes-podcast/assets/69306070/b26ffffe-b044-4825-a8eb-ad2c3d71afed)

**Comment by sonicfutures** [comment]
@Jenya-design I really like these thank you so much!!! 

Would it be possible to get the .AI files of these ones?:
- https://drive.google.com/file/d/1hMYcwvU_Btoo57waIup4KlUYc6cFMEf4/view?usp=drive_link
- https://drive.google.com/file/d/1SMXZfV-xA5o_NoUmsOZ34tiNo4YaIjP8/view?usp=drive_link

Please let me know if you have any questions.

**Comment by Jenya-design** [comment]
Thank you @sonicfutures! 

separate ai files for the images you requested 

- [guest thumbnail 3000x3000](https://drive.google.com/file/d/1E_J5PoZdoIxx0YnJFFhkCFCnwu2gfSVw/view?usp=drive_link)
- [general thumbnail 2560x1440](https://drive.google.com/file/d/1NLvCDlG8aZ2ekOPzzjD_IwDUQZjn-qYL/view?usp=sharing)
I updated Sanjay's photo for better quality image

- [folder with linked photos](https://drive.google.com/drive/folders/1BtEdp-egdkcZdv09E-PO1whIpTtIWD01?usp=drive_link)
- [ai file with all thumbnails](https://drive.google.com/file/d/1ebDckxEgoEOs04H7LwYeLU3lA2fMGfrk/view?usp=drive_link)
Let me know if you have any questions or need the adjustments

cc @russelltrow

**Comment by bryaki02** [comment]
@Jenya-design These look great!

**Comment by Jenya-design** [comment]
Oh, sorry @bryaki02 I've just realised I mentioned Russel few times by mistake, thank you for keeping your eye on the issue despite that
